create table restaurants
	(restaurant_id integer PRIMARY KEY,
	 trip_id integer,
	 restaurant_name varchar(50),
	 cuisine_type varchar(30),
	 address_line_1 varchar(100),
	 address_line_2 varchar(100),
	 city varchar(50),
	 state varchar(30),
	 zipcode varchar(10),
	 country varchar(10),
	 reservation_time timestamp,
	 number_of_people integer,
	 price_range varchar(10),
	 reservation_status varchar(30),
	 sync_status varchar(30),
	 votes integer,
	 added_by integer,
     added_at timestamp);
