create table accomodations
	(accomodation_id integer PRIMARY KEY,
	 trip_id integer PRIMARY KEY,
	 accomodation_number int PRIMARY KEY,
	 accomodation_name varchar(50),
	 accomodation_type varchar(30),
	 address_line_1 varchar(100),
	 address_line_2 varchar(100),
	 city varchar(50),
	 state varchar(30),
	 zipcode varchar(10),
	 country varchar(10),
	 check_in_date date,
	 check_out_date date,
	 number_of_people integer,
	 cost_per_night float,
	 total_cost float,
	 currency_code varchar(5),
	 votes integer,
	 booking_status varchar(30),
	 sync_status varchar(30),
	 added_by integer,
     added_at timestamp);
