create table flights
	(flight_id integer PRIMARY KEY,
	 trip_id integer,
	 trip_flight_number integer,
	 flight_number integer,
	 airline varchar(5),
	 currency_code varchar(5),
	 departure_airport varchar(5),
	 arrival_airport varchar(5),
	 departure_time timestamp,
	 arrival_time timestamp,
	 price float,
	 votes integer,
	 booking_status varchar(30),
	 sync_status varchar(30),
	 added_by integer,
     added_at timestamp);
