create table activities
	(activity_id integer PRIMARY KEY,
	 trip_id integer,
	 activity_name varchar(50),
	 activity_description varchar(200),
	 address_line_1 varchar(100),
	 address_line_2 varchar(100),
	 city varchar(50),
	 state varchar(30),
	 zipcode varchar(10),
	 country varchar(10),
	 activity_date timestamp,
	 rating float,
	 price float,
	 votes integer,
	 booking_status varchar(30),
	 sync_status varchar(30),
	 added_by integer,
     added_at timestamp);
